### ISSUE TITLE
Generate directories and files

### ISSUE THREAD

**Issue by testica** [zoitravel/generator-zoi#1]
Generate directories and files of specific module - *Files are empty*
The module is specified via a command line argument  ```yo zoi name_of_module``` e.g. ```yo zoi users```

**Comment by ShadowManu** [comment]
I don't think you wanted to close this issue. Check it back and reconfirm @testica

**Comment by testica** [comment]
Hey, why not? Do you have problems with the generator? @ShadowManu

**Comment by testica** [comment]
minor fix about name convention - bd73f58ac96cb298c0aa37d69f47548a2948bd47

**Comment by ShadowManu** [comment]
You merged the branch `feat\2`, closing the issue #1. Didn't look like what you intended to do and just checking that out.

**Comment by testica** [comment]
Yes, it was a mistake, anyway I wanted to close this issue. @ShadowManu
