### ISSUE TITLE
Publishing on npm

### ISSUE THREAD

**Issue by ShadowManu** [zoitravel/generator-zoi#3]
On @jcao02's request, I can publish on ZOI npm, but this requires some configuration and testing:

* [Configure the main property on package.json](https://docs.npmjs.com/misc/developers#the-package-json-file)
* [Verify the project works as expected](https://docs.npmjs.com/misc/developers#before-publishing-make-sure-your-package-installs-and-works). In this case, we are working with a CLI tool, so the testing is a little different. Still, try to check that installing your tool works.

After that, notify me on this issue so I go publish it.

**Comment by testica** [comment]
@ShadowManu I think that it is ready. Check last commit 9c008e8a67d811d14edcb7955f0ca76b11859b6c

**Comment by ShadowManu** [comment]
[Package is now published on npm](https://www.npmjs.com/package/generator-zoi). Keep up the good work and put now the `npm install -g generator-zoi` command on the documentation whenever possible.
