### ISSUE TITLE
lingo package deprecated

### ISSUE THREAD

**Issue by ShadowManu** [zoitravel/generator-zoi#4]
When installing the generator, and consequentially the `lingo` package, it warns about it being abandoned. For safety purposes, considering using an alternative. A tool I'm actually working on makes usage of the [inflection package](https://www.npmjs.com/package/inflection). Check it out and see if it suits your use cases.

**Comment by testica** [comment]
@ShadowManu It was replaced - fedeb11222e1bbe34c9abcfadadac20db94950da
